extends:
  - airbnb

env:
  browser: true
  node: true

rules:
  no-console: off

  react/jsx-filename-extension: off
  import/order:
    - error
    - groups:
      - [builtin, external, internal]
      - [sibling, parent, index]
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false
